### ISSUE TITLE
Getting this error! what can i do ?

### ISSUE THREAD

**Issue by post-master** [TDenisM/DISNEY-4K-SCRIPT#1]
Getting this error! what can i do ?

`Downloading video...
2022-01-24 09:18:10 AM - urllib3.connectionpool - 228 - DEBUG - Starting new HTTP connection (1): vod-ftc-na-west-2.media.dssott.com:80
2022-01-24 09:18:11 AM - urllib3.connectionpool - 4JUdGzvrMFDWrUUwY3toJATSeNwjn54LkCnKBPRzDuhzi5vSepHfUckJNxRL2gjkNrSqtCoRUrEDAgRwsQvVCjZbRyFTLRNyDmT1a1boZV-af5d-4a22f353e21d/r/bc9a9a67-a401-4b2d-ba81-fe9508965254/3539-MAIN/02/8500_complete.m3u8 HTTP/1.1" 200 1061
[#8d37fb 7.2MiB/7.4MiB(97%) CN:1 DL:153KiB ETA:1s]Done!

Merging: Far From the Tree 2021 [1080p] [HDR].mp4 [####################] 100%
Done!

Downloading audio...

English - audio
Far From the Tree 2021 eng.mp4
downloaded previously.

Downloading subtitles...
English - has already been successfully downloaded previously.
Traceback (most recent call last):
  File "C:\Disney-Plus-video-downloader\disneyplus.py", line 799, in <module>
    main(episodename=name, seasonfolder=None, m3u8Url=url, SHOW=False)
  File "C:\Disney-Plus-video-downloader\disneyplus.py", line 728, in main
    namer.rename(
  File "C:\Disney-Plus-video-downloader\pydisney\namehelper.py", line 11, in rename
    media_info = MediaInfo.parse(file)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pymediainfo\__init__.py", line 494, in parse
    raise FileNotFoundError(filename)
FileNotFoundError: Far From the Tree 2021.mkv

C:\Disney-Plus-video-downloader>`

**Comment by hihaozhe** [comment]
Disney cannot decrypt without L1 cdm

**Comment by post-master** [comment]
> Disney cannot decrypt without L1 cdm

can I have your discord or telegram?

**Comment by kitty801** [comment]
I can't download any movie.
Always I get an error:
`looks like you entered wrong disney url movie/show type.
url must contain: (disneyplus.com)`


Even Loki TV series as is in how.to.use.txt file
What is wrong?
